<template>
  <div style="height: calc(50vh - 18px); position: relative;">
    <div slot="header" class="clearfix">
      <span style="line-height: 36px; padding: 10px;">Response</span>
      <el-tag
          v-if="preflight"
          style="position: absolute; right: 10px; top: 5px;"
          type="primary">
        Preflight could be generated by browser
      </el-tag>
    </div>
    <tree-view
        style="color: #fff; background: #777; padding: 10px; position: absolute; top: 50px; bottom: 0; left: 0; right: 0;"
        :data="shared.response"
        :options="{rootObjectKey: 'response', maxDepth: 500}">
    </tree-view>
  </div>
</template>

<script>
  export default {
    name: 'requester',
    props: [
      'shared'
    ],
    computed: {
      preflight () {
        return true // @todo - check by preflight routine from shared.request
      }
    }
  }
</script>

<style>
</style>
