<template>
  <div>
    <div slot="header" class="clearfix">
      <span style="line-height: 36px;">Response</span>
      <el-tag
          v-if="preflight"
          style="float: right"
          type="primary">
        Preflight could be generated by browser
      </el-tag>
    </div>
    <tree-view
        :data="shared.response"
        :options="{rootObjectKey: 'response', maxDepth: 500}">
    </tree-view>
  </div>
</template>

<script>
  export default {
    name: 'requester',
    props: [
      'shared'
    ],
    computed: {
      preflight () {
        return true // @todo - check by preflight routine from shared.request
      }
    }
  }
</script>

<style>
</style>
