/**
 * Autogenerated by papir 0.0.1
 */

import Model from '../model'

/**
 * ProductModel
 */
export default class ProductModel extends Model {

  constructor () {
    super({
      type: 'map',
      map: 'product'
    })

    this.id = () => {
      return ''
    }
  }

}